# Jekyll - Config file
#
# Site settings - To personalise the website

title: Global Assessment of the Cooling and Heating Demand for Brussels energetic future
description: >- # this means to ignore newlines until next object
  Dimitri Hanssens | PhD Candidate @ ATM & Brussels Environment | Explainable machine learning applied to the development of smart grids
baseurl: "/" # subpath of the site, e.g. /blog
url: "http://dimhanssens.github.io"

# Build settings
theme: jekyll-theme-cayman